### ISSUE TITLE
benchpark setup picks up .swp files from the machine config dir and crashes

### ISSUE THREAD

**Issue by pszi1ard** [LLNL/benchpark#145]
Vim swap files from the machine config directory seemed to get picked up and passed to ramble which throws a utf-8 decoding error shown below.

Steps to reproduce below,`compilers.yaml` was opened in vim before running `benchpark setup`.

```
$benchpark setup gromacs/openmp LUMI-C-HPECray-zen3-MI250X-Slingshot ./
[...]

$. ./setup.sh

$ ramble -d -P -D gromacs/openmp/LUMI-C-HPECray-zen3-MI250X-Slingshot/workspace workspace setup
==> [2024-02-22-16:36:41.239885] In workspace init. Root = gromacs/openmp/LUMI-C-HPECray-zen3-MI250X-Slingshot/workspace
==> [2024-02-22-16:36:41.246624] '/usr/bin/git' '-C' '/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble' 'rev-parse' 'HEAD'
==> [2024-02-22-16:36:41.254788] '/usr/bin/git' '-C' '/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble' 'rev-parse' 'HEAD'
==> [2024-02-22-16:36:41.262421] '/usr/bin/git' '-C' '/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/spack' 'rev-parse' 'HEAD'
/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_4/gromacs/openmp/LUMI-C-HPECray-zen3-MI250X-Slingshot/workspace/configs/auxiliary_software_files/packages.yaml
/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_4/gromacs/openmp/LUMI-C-HPECray-zen3-MI250X-Slingshot/workspace/configs/auxiliary_software_files/modules.yaml
/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_4/gromacs/openmp/LUMI-C-HPECray-zen3-MI250X-Slingshot/workspace/configs/auxiliary_software_files/.compilers.yaml.swp
Traceback (most recent call last):
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/bin/ramble", line 70, in <module>
    sys.exit(ramble.main.main())
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/lib/ramble/ramble/main.py", line 909, in main
    return _main(argv)
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/lib/ramble/ramble/main.py", line 810, in _main
    ws = ramble.cmd.find_workspace(args)
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/lib/ramble/ramble/cmd/__init__.py", line 280, in find_workspace
    return ramble.workspace.Workspace(ws)
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/lib/ramble/ramble/workspace/workspace.py", line 522, in __init__
    self._read()
  File "/pfs/lustrep3/scratch/project_465000810/szpall/benchpark_tests_2/ramble/lib/ramble/ramble/workspace/workspace.py", line 581, in _read
    self._read_auxiliary_software_file(filename, f.read())
  File "/opt/cray/pe/python/3.10.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 16: invalid continuation byte
```

**Comment by scheibelp** [comment]
This should be resolved by https://github.com/LLNL/benchpark/pull/162 (which has been merged). Feel free to reopen if you see the problem again.
