### ISSUE TITLE
Better formatting for subprocess errors

### ISSUE THREAD

**Issue by dyokelson** [LLNL/benchpark#417]
When an error is generated from a subprocess, the actual error is displayed in the console but it's very hidden. It would be ideal to elevate these so that the user doesn't see the information about the subprocess call and just sees the relevant error. This should apply to any error that occurs in a subprocess.

Example:

$ ./bin/benchpark system init --dest=ruby-system cts cluster=ruby
Hold tight, Benchpark is bootstrapping itself.
Hold tight, Benchpark is bootstrapping itself.
Hold tight, Benchpark is bootstrapping itself.
Hold tight, Benchpark is bootstrapping itself.
Hold tight, Benchpark is bootstrapping itself.
/g/g19/brink2/.benchpark/ramble/lib/ramble/ramble/repository.py:1006: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  yaml_data = yaml.load(reponame_file)
**Abort: system description dir already exists (ruby-system) <-- HERE!**
Traceback (most recent call last):
  File "/usr/WS1/brink2/benchpark-pythonvenv/benchpark-exit-modifier/./bin/benchpark", line 21, in <module>
    main()
  File "/usr/WS1/brink2/benchpark-pythonvenv/benchpark-exit-modifier/./bin/benchpark", line 17, in main
    subprocess.run([sys.executable, main_py] + sys.argv[1:], check=True)
  File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/view/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/WS2/benchpark-dev/benchpark-venv/toss_4_x86_64_ib/bin/python3', PosixPath('/usr/WS1/brink2/benchpark-pythonvenv/benchpark-exit-modifier/lib/main.py'), 'system', 'init', '--dest=ruby-system', 'cts', 'cluster=ruby']' returned non-zero exit status 1.

**Comment by scheibelp** [comment]
At this point we've removed the

`Hold tight, Benchpark is bootstrapping itself.`

part, and we've updated to a version of Ramble that does `safe_load`.

So the real error 

`Abort: system description dir already exists (ruby-system) `

should come first for a current checkout of benchpark now.
